### ISSUE TITLE
How can i add minimum error level

### ISSUE THREAD

**Issue by technosml** [designmynight/laravel-log-mailer#3]
I just want to know how can I add minimum logging level to mail logging driver. I have added 
`'level' => 'critical',`
this line of code after 
`'driver' => 'mail',`
but its mailing all the error from all levels.

**Comment by StevePorter92** [comment]
Thanks @technosml. Fixed in v1.0.2, it wasn't respecting the level passed into configuration

**Comment by technosml** [comment]
Thank you Steve
